version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest
    ports:
      - '8181:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/Rest
    depends_on:
      - db_pg_15

  db_pg_15:
    image: postgres:15-alpine
    container_name: db
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: Rest
      POSTGRES_USER: rest-postgres
      POSTGRES_PASSWORD: rest-postgres